from handlers.collection_handler import CollectionHandler
from handlers.document_handler import DocumentHandler
from handlers.link_handler import LinkHandler
from handlers.text_handler import TextHandler
from handlers.upload_handler import PDFUploadHandler
