name: Integration tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pytest
      run: |
        pip install pytest
    - uses: actions/checkout@v3
    - name: Check envs in config
      run: docker compose config
    - name: Start containers
      run: docker compose up -d --build
    - name: Wait for complete startup for 30s
      run: sleep 30s
      shell: bash
    - name: Check logs after startup
      if: always()
      run: docker compose logs backend
    - name: Test with pytest
      run: |
        pytest tests -s
    - name: Check logs after tests
      run: docker compose logs backend
    - name: Stop containers
      if: always()
      run: docker compose down
