name: Integration tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check envs in config
      run: docker compose config
    - name: Start containers
      run: docker compose up -d --build
    - name: Wait for FastAPI server
      uses: cygnetdigital/wait_for_response@v2.0.0
      with:
        url: 'http://0.0.0.0:4000/docs'
        responseCode: '200'
        timeout: 30000
        interval: 1000
    - name: Check logs
      if: always()
      run: docker compose logs backend
    - name: Run tests
      if: always()
      run: |
        curl -X GET http://0.0.0.0:4000/v1/info
        curl -X GET http://localhost:4000/v1/info
    - name: Stop containers
      if: always()
      run: docker compose down
