name: Integration tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Start containers
      run: docker compose up -d --build
    - name: Run tests
      run: |
        curl -X GET http://localhost:4000/v1/info
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
