name: Integration tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Start containers
      run: docker compose up -d --build
    - name: Wait for FastAPI server
      timeout-minutes: 1
      run: |
        url="http://localhost:4000/docs"
        while true; do
          status_code=$(curl --write-out '%{http_code}' --silent --output /dev/null "$url")
          if [ "$status_code" -eq 200 ]; then
            echo "FastAPI server is up and running."
            break
          else
            echo "FastAPI server is not up yet. Waiting..."
            sleep 5
          fi
        done
    - name: Check logs
      run: docker compose logs backend
    - name: Run tests
      run: |
        curl -X GET http://localhost:4000/v1/info
    - name: Stop containers
      if: always()
      run: docker compose down
